### ISSUE TITLE
Update to sql.js 1.0.0

### ISSUE THREAD

**Issue by omkar1707** [coturiv/ionic-typeorm-starter#8]
How to use sql-wasm.js instead of sql.js.?

`new webpack.ProvidePlugin({
            'window.SQL': 'sql.js/dist/sql-wasm.js'
        })`

**Comment by coturiv** [comment]
It is resolved in this [update](https://github.com/coturiv/ionic-typeorm-starter/commit/8f9ca7f3e66da87535469825eccd8a71eeb19070) 🎉
